Update design
AbhishekkM05/Mobile-Portfolio- pull request #1
Opened 2022-07-01 18:11 UTC by AbhishekkM05

2022-07-01 20:02 UTC, rloterh requested changes
Hi Abhishek, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Design matches the provided Figma template


## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly check the comments marked **[OPTIONAL]** under the review._

You can also consider:
- Kindly endeavor to add an appropriate project name/ Title head in your ReadMe
<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 04:22 UTC, Ismailco approved these changes
### Hi @AbhishekkM05, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-07-02 04:22 UTC, Ismailco commented on index.html
> +        <div class="Main-container"><p>My Logo</p>
- [ ] [OPTIONAL] Kindly consider using an `a` tag for the logo so it can be a link

2022-07-02 04:22 UTC, Ismailco commented on index.html
> +<footer></footer>
- [ ] [OPTIONAL] If a section is unnecessary kindly remove it from your code, this will make your code cleaner

2022-07-02 04:22 UTC, Ismailco commented on index.html
> +<!DOCTYPE html>
- [ ] [OPTIONAL] Your PR doesn't have a description, kindly add your changes to the PR description

2022-07-02 06:10 UTC, merged